# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# First define some variables
varTotal=0	# running total
varOldNo=1	# previous number to be added to the current number in sequence for fibonacci number. preset to 1 to start the sequence
varOlderNo=0	# previous number to be added to the current number in sequence for fibonacci number
varFibNo=0		# current fibonacci number.
# loop through all numbers
while True:
	# Add the two old numbers together to get the next in sequence
	varFibNo= varOldNo + varOlderNo
	# check we are still under 4 million
	if varFibNo > 4000000:
		break
	# shuffle the old numbers, will add them together on next loop
	varOlderNo = varOldNo
	varOldNo = varFibNo
	# check if thus number is even-valued
	if varFibNo % 2 == 0:
	# add even number to our running total
		varTotal+=varFibNo
		print(varFibNo)

#at completion of loop, print the running total	
print('Total:',varTotal)
	